# Generated by Django 3.2.25 on 2024-07-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0016_alter_ventas_total_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recibo_Reserva',
        ),
    ]
