# Generated by Django 3.2.25 on 2024-07-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0017_delete_recibo_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo_Reserva',
            fields=[
                ('id_re', models.AutoField(primary_key=True, serialize=False)),
                ('total_re', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision_re', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.clientes')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.reservas')),
            ],
        ),
    ]
