# Generated by Django 3.2.25 on 2024-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0018_recibo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ultima_recomendacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
