# Generated by Django 3.2.25 on 2024-08-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0019_clientes_ultima_recomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_favoritas', models.TextField()),
                ('actualizacion_fecha', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.clientes')),
                ('menus_favoritos', models.ManyToManyField(blank=True, to='Restaurante.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInteracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(max_length=50)),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.clientes')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.menus')),
            ],
        ),
    ]
