# Generated by Django 3.2.25 on 2024-08-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0020_historialinteracciones_preferenciasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilitudUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similitud', models.FloatField()),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario1', to='Restaurante.clientes')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario2', to='Restaurante.clientes')),
            ],
            options={
                'unique_together': {('usuario1', 'usuario2')},
            },
        ),
    ]
