# Generated by Django 3.2.25 on 2024-08-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0023_interaccion_recomendacion_similitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='similitud',
            name='usuario1',
        ),
        migrations.RemoveField(
            model_name='similitud',
            name='usuario2',
        ),
        migrations.DeleteModel(
            name='Interaccion',
        ),
        migrations.DeleteModel(
            name='Recomendacion',
        ),
        migrations.DeleteModel(
            name='Similitud',
        ),
    ]
