# Generated by Django 3.2.25 on 2024-08-20 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0024_auto_20240809_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_reservas',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ventas',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.menus'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.mesas'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Restaurante.reservas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Detalles_Ventas',
        ),
    ]
